name: Build Docker Image
description: "Build Docker image for ACM Website Server"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile.dev
        tags: acm-website-server:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify image
      shell: bash
      run: docker image inspect acm-website-server:latest
