/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as OnboardingImport } from "./routes/onboarding";
import { Route as LoginImport } from "./routes/login";
import { Route as EventsImport } from "./routes/events";
import { Route as AboutImport } from "./routes/about";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute
} as any);

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute
} as any);

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute
} as any);

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface AdminLayoutRouteChildren {
  AdminLayoutProjectsRoute: typeof AdminLayoutProjectsRoute;
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute;
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute;
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutProjectsRoute: AdminLayoutProjectsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute
};

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(AdminLayoutRouteChildren);

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/events" | "/login" | "/onboarding";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/events" | "/login" | "/onboarding";
  id: "__root__" | "/" | "/about" | "/events" | "/login" | "/onboarding";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  EventsRoute: typeof EventsRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dashboard",
        "/login",
        "/onboarding",
        "/profile",
        "/projects",
        "/admin",
        "/events/$eventId",
        "/events/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/_layout"
      ]
    },
    "/admin/_layout": {
      "filePath": "admin/_layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_layout/projects",
        "/admin/_layout/users",
        "/admin/_layout/"
      ]
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx"
    },
    "/admin/_layout/projects": {
      "filePath": "admin/_layout/projects.tsx",
      "parent": "/admin/_layout"
    },
    "/admin/_layout/users": {
      "filePath": "admin/_layout/users.tsx",
      "parent": "/admin/_layout"
    },
    "/admin/_layout/": {
      "filePath": "admin/_layout/index.tsx",
      "parent": "/admin/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
