services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - public
    depends_on:
      server:
        condition: service_healthy
        restart: true

  server:
    image: manasc478/acm-website-server:latest
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - private
      - public
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:5001"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  db:
    image: postgres:latest
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - private

volumes:
  acm_website_db_data:

networks:
  public:
  private:
    ipam:
      config:
        - subnet: "192.0.0.0/24"
          gateway: "192.0.0.1"

configs:
  nginx_config:
    file: ./nginx.conf
