services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
      - client_dist:/usr/share/nginx/html:ro

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
    volumes:
      - client_dist:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging

  db:
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts/staging:/docker-entrypoint-initdb.d/

volumes:
  client_dist:
