services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
      - ./client/dist:/usr/share/nginx/html:ro

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging

  db:
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts/staging:/docker-entrypoint-initdb.d/

  certbot:
    image: certbot/certbot:v5.0.0
    volumes:
      - ./certbot/www/:/var/www/certbot:rw
      - ./certbot/conf/:/etc/letsencrypt:rw
    entrypoint: 
