services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.staging
    container_name: acm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
      - /var/log/nginx/acmwebsite/error.log:/var/log/nginx/error.log
      - /var/log/nginx/acmwebsite/access.log:/var/log/nginx/access.log
    depends_on:
      server:
        condition: service_healthy
        restart: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    container_name: acm-server
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=${NODE_ENV?REQUIRED}
      - PORT=${PORT?REQUIRED}
      - POSTGRES_HOST=${POSTGRES_HOST?REQUIRED}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER?REQUIRED}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?REQUIRED}
      - POSTGRES_DB=${POSTGRES_DB?REQUIRED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID?REQUIRED}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET?REQUIRED}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI?REQUIRED}
      - ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID?REQUIRED}
      - SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY?REQUIRED}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME?REQUIRED}
      - S3_DEFAULT_IMAGE_PLACEHOLDER=${S3_DEFAULT_IMAGE_PLACEHOLDER?REQUIRED}
      - S3_BUCKET_URL=${S3_BUCKET_URL?REQUIRED}
      - SQS_QUEUE_URL=${NOTIFICATION_SERVICE_QUEUE_URL?REQUIRED}
      - REGION=${AWS_REGION?REQUIRED}
      - ROLE_ARN=${AWS_ROLE_ARN?REQUIRED}
      - SENDER=${EMAIL_SENDER?REQUIRED}
      - APPLICATION=${APPLICATION?REQUIRED}
      - CORS_ORIGINS=${CORS_ORIGINS?REQUIRED}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL?REQUIRED}
      - GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?REQUIRED}
      - GOOGLE_SHEETS_MEMBERS_ID=${GOOGLE_SHEETS_MEMBERS_ID?REQUIRED}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 5s

  db:
    image: postgres:17
    container_name: acm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER?REQUIRED}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?REQUIRED}
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts/staging:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER?REQUIRED}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  acm_website_db_data:
