services:
  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      client:
        condition: service_healthy
        restart: true
      server:
        condition: service_healthy
        restart: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV?REQUIRED}
    depends_on:
      server:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=${NODE_ENV?REQUIRED}
      - PORT=${PORT?REQUIRED}
      - POSTGRES_HOST=${POSTGRES_HOST?REQUIRED}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER?REQUIRED}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?REQUIRED}
      - POSTGRES_DB=${POSTGRES_DB?REQUIRED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID?REQUIRED}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET?REQUIRED}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI?REQUIRED}
      - ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID?REQUIRED}
      - SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY?REQUIRED}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME?REQUIRED}
      - S3_DEFAULT_IMAGE_PLACEHOLDER=${S3_DEFAULT_IMAGE_PLACEHOLDER?REQUIRED}
      - S3_BUCKET_URL=${S3_BUCKET_URL?REQUIRED}
      - SQS_QUEUE_URL=${NOTIFICATION_SERVICE_QUEUE_URL?REQUIRED}
      - REGION=${AWS_REGION?REQUIRED}
      - ROLE_ARN=${AWS_ROLE_ARN?REQUIRED}
      - SENDER=${EMAIL_SENDER?REQUIRED}
      - APPLICATION=${APPLICATION?REQUIRED}
      - CORS_ORIGINS=${CORS_ORIGINS?REQUIRED}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 5s

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER?REQUIRED}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?REQUIRED}
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts/dev:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER?REQUIRED}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  acm_website_db_data:
