services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    volumes:
      - acm_website_db_data:/var/lib/postgresql/data
      - ./db-scripts/dev:/docker-entrypoint-initdb.d/
