\c acm_website

insert into majors(name) values
('Undeclared'),
('Advertising, BS'),
('Aerospace Engineering, BS'),
('African American Studies, BA'),
('Animation & Illustration, BFA'),
('Anthropology, BA'),
('Anthropology, BA (SJSU Online)'),
('Applied Mathematics, Applied and Computational Mathematics Concentration, BS'),
('Art History and Visual Culture, BA'),
('Art, Digital Media Art Concentration, BFA'),
('Art, Photography Concentration, BFA'),
('Art, Pictorial Art Concentration, BFA'),
('Art, Spatial Art Concentration, BFA'),
('Art, Studio Practice Concentration (Preparation for Teaching), BA'),
('Art, Studio Practice Concentration, BA'),
('Aviation, BS'),
('Behavioral Science, BA'),
('Biological Sciences - Ecology and Evolution, BS'),
('Biological Sciences - Marine Biology, BS'),
('Biological Sciences, BA'),
('Biological Sciences, Microbiology Concentration, BS'),
('Biological Sciences, Molecular Biology Concentration, BS'),
('Biological Sciences, Systems Physiology Concentration, BS'),
('Biomedical Engineering, BS  '),
('Business Administration, Accounting Concentration, BS'),
('Business Administration, Accounting Information Systems Concentration, BS'),
('Business Administration, Business Analytics Concentration, BS'),
('Business Administration, Corporate Accounting and Finance Concentration, BS'),
('Business Administration, Entrepreneurship Concentration, BS'),
('Business Administration, Finance Concentration, BS'),
('Business Administration, General Business Concentration, BS'),
('Business Administration, General Business Concentration, BS (SJSU Online)'),
('Business Administration, Hospitality, Tourism and Event Management Concentration, BS'),
('Business Administration, Human Resource Management Concentration, BS'),
('Business Administration, International Business Concentration, BS'),
('Business Administration, Management Concentration, BS'),
('Business Administration, Management Information Systems Concentration, BS'),
('Business Administration, Marketing Concentration, BS'),
('Business Administration, Operations and Supply Chain Management Concentration, BS'),
('Chemical Engineering, BS '),
('Chemistry, BA'),
('Chemistry, Biochemistry Concentration, BS'),
('Chemistry, BS '),
('Chicana and Chicano Studies, BA'),
('Child and Adolescent Development, BA'),
('Child and Adolescent Development, Preparation for Teaching W/CSET Waiver, BA'),
('Child and Adolescent Development, Preparation for Teaching, BA'),
('Chinese, BA'),
('Civil Engineering, BS'),
('Climate Science, BS'),
('Communication Studies, BA'),
('Communication Studies, Preparation for Teaching, BA (Not Accepting Students)'),
('Communicative Disorders and Sciences, BA'),
('Computer Engineering, BS'),
('Computer Science and Linguistics, BS'),
('Computer Science, BS'),
('Creative Arts, BA'),
('Dance, BA'),
('Dance, BFA'),
('Data Science, BS'),
('Design Studies, BA'),
('Earth System Science, BS'),
('Economics, BA'),
('Economics, BA (SJSU Online)'),
('Economics, BS'),
('Electrical Engineering, BS '),
('Engineering Technology, Computer Network System Management Concentration, BS'),
('Engineering Technology, Manufacturing Systems Concentration, BS'),
('English, BA'),
('English, Creative Writing Concentration, BA'),
('English, Preparation for Teaching (Single Subject), BA'),
('English, Professional and Technical Writing Concentration, BA'),
('Environmental Studies, BA'),
('Environmental Studies, BS'),
('Environmental Studies, Preparation for Teaching, BA'),
('Forensic Science, Biology Concentration, BS'),
('Forensic Science, Chemistry Concentration, BS'),
('Forensic Science, Crime Scene Investigation Concentration, BS'),
('Forensic Science, Digital Evidence Concentration, BS'),
('French, BA'),
('Geographic Information Science (GIS), BS'),
('Geography, BA'),
('Geology, BS'),
('Global Studies, BA'),
('Graphic Design, BFA'),
('History, BA'),
('Humanities, American Studies Concentration, BA'),
('Humanities, Liberal Arts Concentration, BA'),
('Humanities, Religious Studies Concentration, BA'),
('Industrial and Systems Engineering, BS'),
('Industrial Design, BS'),
('Information Science and Data Analytics, BS'),
('Information Science and Data Analytics, BS (SJSU Online)'),
('Interdisciplinary Engineering, BS'),
('Interdisciplinary Engineering, BS (SJSU Online) (Currently Not Accepting Students)'),
('Interdisciplinary Studies, Educational and Community Leadership Concentration, BA (SJSU Online)'),
('Interior Design, BFA'),
('Japanese, BA'),
('Journalism, BS'),
('Justice Studies, BS'),
('Justice Studies, Criminology Concentration, BS'),
('Kinesiology, BS'),
('Kinesiology, Preparation for Teaching, BS'),
('Liberal Studies, Integrated Teacher Education Program Spanish Bilingual, BA'),
('Liberal Studies, Integrated Teacher Education Program, BA'),
('Liberal Studies, Preparation for Teaching, BA'),
('Linguistics, BA'),
('Materials Engineering, BS'),
('Mathematics, BA'),
('Mathematics, Integrated Teacher Education Program, BA'),
('Mechanical Engineering, BS'),
('Meteorology, BS'),
('Music, BA'),
('Music, Composition Concentration, BM'),
('Music, Jazz Studies Concentration, BM'),
('Music, Music Education Concentration, BM'),
('Music, Performance Concentration, BM'),
('Nursing, BS'),
('Nursing, Concurrent Enrollment Program (CEP) ADN to BSN'),
('Nursing, RN to BSN Concentration, BSN'),
('Nutritional Science, Applied Nutrition and Food Sciences Concentration, BS'),
('Nutritional Science, Dietetics Concentration, BS'),
('Nutritional Science, Food Management Concentration, BS'),
('Organizational Studies, BA'),
('Packaging, BS'),
('Philosophy, BA'),
('Physics, BA'),
('Physics, BS'),
('Physics, Preparation for Teaching, BA'),
('Political Science, BA'),
('Psychology, BA'),
('Public Health, BS'),
('Public Health, BS (SJSU Online)'),
('Public Health, Concentration in Community Health Education, BS'),
('Public Health, Concentration in Population Data Science, BS'),
('Public Relations, BS'),
('Public Relations, BS (SJSU Online)'),
('Radio-Television-Film, BA'),
('Recreation, BS'),
('Recreation, Recreation Management Concentration, BS'),
('Recreation, Recreation Therapy Concentration, BS'),
('Social Science, Preparation for Teaching (Single Subject), BA'),
('Social Work, BA'),
('Sociology, BA'),
('Sociology, Community Change Concentration, BA'),
('Sociology, Race and Ethnic Studies Concentration, BA'),
('Sociology, Social Interaction Concentration, BA (Not Accepting Students)'),
('Software Engineering, BS'),
('Spanish, BA'),
('Statistics, BS '),
('Theatre Arts, BA'),
('Theatre Arts, Preparation for Teaching, BA (Not accepting students)'),
('Women, Gender, and Sexuality Studies, BA');

insert into files(key, name) values
('default/image-placeholder.svg', 'Default Image');

INSERT INTO club_links(instagram, discord, linkedin, member_application) VALUES
('https://www.instagram.com/sjsuacm/', 'https://discord.gg/Rw85ngkExu', 'https://www.linkedin.com/company/sjsu-computer-science-club/about/', 'https://docs.google.com/forms/d/e/1FAIpQLSfNBu-IGm7bhUmMf2cSOmNca3SiJZyVRzPBVTVOYVBNZIyeYA/viewform?pli=1');

INSERT INTO landing_questions(question, answer) VALUES
($$Who's allowed to join this club?$$, $$ACM@SJSU is open to all SJSU students, regardless of their major!$$),
($$What are the rules of the club?$$, $$Be respectful, keep the clubroom clean, and have fun!$$),
($$Is there a membership fee for the club?$$, $$Yes. It's $20 for 1 semester or $30 for 2 semesters$$),
($$What do I get for a paid membership?$$, $$Paid members are invited to attend exclusive networking sessions, tech talks, and company events. We collaborate with many industry leaders, including Google, Tesla, and Nvidia, so don''t miss out!$$);
