FROM oven/bun:1.2-alpine AS base

FROM base AS builder

RUN apk add --no-cache curl
WORKDIR /app

COPY package.json bun.lockb tsconfig.json* ./
RUN bun install --frozen-lockfile --production

COPY src ./src
RUN bun build ./src/index.ts --outdir ./dist --minify --sourcemap --target bun

FROM base AS runner
RUN apk add --no-cache curl
WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json

CMD ["bun", "/app/dist/index.js"]

