user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
      listen 80;
      listen [::]:80;
      server_name staging.acmsjsu.org www.staging.acmsjsu.org;
      root /var/www/certbot;

      location /.well-known/acme-challenge/ {
	      allow all;
      }
      location /healthcheck.txt {
	      allow all;
      }
    }
}
