user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format proxy_log '$remote_addr - $remote_user [$time_local] '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent" '
                     'upstream: $upstream_addr '
                     'status: $upstream_status '
                     'response_time: $upstream_response_time';

    upstream server_upstream {
        server server:5001;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name staging.acmsjsu.org www.staging.acmsjsu.org;

      location /.well-known/acme-challenge/ {
        root /var/www/certbot;
      }

      location / {
        return 301 https://$host$request_uri;
      }
    }

    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name staging.acmsjsu.org www.staging.acmsjsu.org;

      ssl_certificate /etc/letsencrypt/live/staging.acmsjsu.org/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/staging.acmsjsu.org/privkey.pem;

      location /api/ {
      	  access_log /var/log/nginx/access.log proxy_log;
          proxy_pass http://server_upstream/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
      }
    }

    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      listen 443 ssl default_server;
      listen [::]:443 ssl default_server;

      ssl_certificate /etc/letsencrypt/live/staging.acmsjsu.org/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/staging.acmsjsu.org/privkey.pem;

      return 444;
    }
}
