# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "us-west-2-global-terraform-state-backend"
    dynamodb_table = "global_terraform_state_locking"
    encrypt        = true
    key            = "service/acm-website/./terraform.tfstate"
    region         = "us-west-2"
  }
}
