# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        provider "aws" {
            region = "us-west-2"
            assume_role {
              role_arn = "arn:aws:iam::588738592350:role/AcmApplicationRoleForLocalTerraform"
              session_name = "terragrunt-AcmApplicationRoleForLocalTerraform-session"
            }
        }
