insert into majors(name) values
('Undeclared'),
('Advertising, BS'),
('Aerospace Engineering, BS'),
('African American Studies, BA'),
('Animation & Illustration, BFA'),
('Anthropology, BA'),
('Anthropology, BA (SJSU Online)'),
('Applied Mathematics, Applied and Computational Mathematics Concentration, BS'),
('Art History and Visual Culture, BA'),
('Art, Digital Media Art Concentration, BFA'),
('Art, Photography Concentration, BFA'),
('Art, Pictorial Art Concentration, BFA'),
('Art, Spatial Art Concentration, BFA'),
('Art, Studio Practice Concentration (Preparation for Teaching), BA'),
('Art, Studio Practice Concentration, BA'),
('Aviation, BS'),
('Behavioral Science, BA'),
('Biological Sciences - Ecology and Evolution, BS'),
('Biological Sciences - Marine Biology, BS'),
('Biological Sciences, BA'),
('Biological Sciences, Microbiology Concentration, BS'),
('Biological Sciences, Molecular Biology Concentration, BS'),
('Biological Sciences, Systems Physiology Concentration, BS'),
('Biomedical Engineering, BS  '),
('Business Administration, Accounting Concentration, BS'),
('Business Administration, Accounting Information Systems Concentration, BS'),
('Business Administration, Business Analytics Concentration, BS'),
('Business Administration, Corporate Accounting and Finance Concentration, BS'),
('Business Administration, Entrepreneurship Concentration, BS'),
('Business Administration, Finance Concentration, BS'),
('Business Administration, General Business Concentration, BS'),
('Business Administration, General Business Concentration, BS (SJSU Online)'),
('Business Administration, Hospitality, Tourism and Event Management Concentration, BS'),
('Business Administration, Human Resource Management Concentration, BS'),
('Business Administration, International Business Concentration, BS'),
('Business Administration, Management Concentration, BS'),
('Business Administration, Management Information Systems Concentration, BS'),
('Business Administration, Marketing Concentration, BS'),
('Business Administration, Operations and Supply Chain Management Concentration, BS'),
('Chemical Engineering, BS '),
('Chemistry, BA'),
('Chemistry, Biochemistry Concentration, BS'),
('Chemistry, BS '),
('Chicana and Chicano Studies, BA'),
('Child and Adolescent Development, BA'),
('Child and Adolescent Development, Preparation for Teaching W/CSET Waiver, BA'),
('Child and Adolescent Development, Preparation for Teaching, BA'),
('Chinese, BA'),
('Civil Engineering, BS'),
('Climate Science, BS'),
('Communication Studies, BA'),
('Communication Studies, Preparation for Teaching, BA (Not Accepting Students)'),
('Communicative Disorders and Sciences, BA'),
('Computer Engineering, BS'),
('Computer Science and Linguistics, BS'),
('Computer Science, BS'),
('Creative Arts, BA'),
('Dance, BA'),
('Dance, BFA'),
('Data Science, BS'),
('Design Studies, BA'),
('Earth System Science, BS'),
('Economics, BA'),
('Economics, BA (SJSU Online)'),
('Economics, BS'),
('Electrical Engineering, BS '),
('Engineering Technology, Computer Network System Management Concentration, BS'),
('Engineering Technology, Manufacturing Systems Concentration, BS'),
('English, BA'),
('English, Creative Writing Concentration, BA'),
('English, Preparation for Teaching (Single Subject), BA'),
('English, Professional and Technical Writing Concentration, BA'),
('Environmental Studies, BA'),
('Environmental Studies, BS'),
('Environmental Studies, Preparation for Teaching, BA'),
('Forensic Science, Biology Concentration, BS'),
('Forensic Science, Chemistry Concentration, BS'),
('Forensic Science, Crime Scene Investigation Concentration, BS'),
('Forensic Science, Digital Evidence Concentration, BS'),
('French, BA'),
('Geographic Information Science (GIS), BS'),
('Geography, BA'),
('Geology, BS'),
('Global Studies, BA'),
('Graphic Design, BFA'),
('History, BA'),
('Humanities, American Studies Concentration, BA'),
('Humanities, Liberal Arts Concentration, BA'),
('Humanities, Religious Studies Concentration, BA'),
('Industrial and Systems Engineering, BS'),
('Industrial Design, BS'),
('Information Science and Data Analytics, BS'),
('Information Science and Data Analytics, BS (SJSU Online)'),
('Interdisciplinary Engineering, BS'),
('Interdisciplinary Engineering, BS (SJSU Online) (Currently Not Accepting Students)'),
('Interdisciplinary Studies, Educational and Community Leadership Concentration, BA (SJSU Online)'),
('Interior Design, BFA'),
('Japanese, BA'),
('Journalism, BS'),
('Justice Studies, BS'),
('Justice Studies, Criminology Concentration, BS'),
('Kinesiology, BS'),
('Kinesiology, Preparation for Teaching, BS'),
('Liberal Studies, Integrated Teacher Education Program Spanish Bilingual, BA'),
('Liberal Studies, Integrated Teacher Education Program, BA'),
('Liberal Studies, Preparation for Teaching, BA'),
('Linguistics, BA'),
('Materials Engineering, BS'),
('Mathematics, BA'),
('Mathematics, Integrated Teacher Education Program, BA'),
('Mechanical Engineering, BS'),
('Meteorology, BS'),
('Music, BA'),
('Music, Composition Concentration, BM'),
('Music, Jazz Studies Concentration, BM'),
('Music, Music Education Concentration, BM'),
('Music, Performance Concentration, BM'),
('Nursing, BS'),
('Nursing, Concurrent Enrollment Program (CEP) ADN to BSN'),
('Nursing, RN to BSN Concentration, BSN'),
('Nutritional Science, Applied Nutrition and Food Sciences Concentration, BS'),
('Nutritional Science, Dietetics Concentration, BS'),
('Nutritional Science, Food Management Concentration, BS'),
('Organizational Studies, BA'),
('Packaging, BS'),
('Philosophy, BA'),
('Physics, BA'),
('Physics, BS'),
('Physics, Preparation for Teaching, BA'),
('Political Science, BA'),
('Psychology, BA'),
('Public Health, BS'),
('Public Health, BS (SJSU Online)'),
('Public Health, Concentration in Community Health Education, BS'),
('Public Health, Concentration in Population Data Science, BS'),
('Public Relations, BS'),
('Public Relations, BS (SJSU Online)'),
('Radio-Television-Film, BA'),
('Recreation, BS'),
('Recreation, Recreation Management Concentration, BS'),
('Recreation, Recreation Therapy Concentration, BS'),
('Social Science, Preparation for Teaching (Single Subject), BA'),
('Social Work, BA'),
('Sociology, BA'),
('Sociology, Community Change Concentration, BA'),
('Sociology, Race and Ethnic Studies Concentration, BA'),
('Sociology, Social Interaction Concentration, BA (Not Accepting Students)'),
('Software Engineering, BS'),
('Spanish, BA'),
('Statistics, BS '),
('Theatre Arts, BA'),
('Theatre Arts, Preparation for Teaching, BA (Not accepting students)'),
('Women, Gender, and Sexuality Studies, BA');

INSERT INTO users (
    id, name, email, major, education_level, grad_date, interests, profile_pic, linkedin, github, website, role, paid 
) VALUES 
('user1', 'Alice Smith', 'alice.smith@example.com', 'Aerospace Engineering, BS', 'undergraduate', '2025-05-15', 
  '{"web development", "machine learning"}', NULL, 'https://linkedin.com', 'https://github.com', NULL, 'user', NULL),
('user2', 'Bob Johnson', 'bob.johnson@example.com', 'Chemistry, BA', 'graduate', '2022-12-10', 
  '{"networking", "cybersecurity"}', NULL, 'https://linkedin.com', 'https://github.com', NULL, 'admin', NULL),
('user3', 'Charlie Brown', 'charlie.brown@example.com', 'History, BA', 'undergraduate', '2026-08-30', 
  '{"mobile development", "game development"}', NULL, 'https://www.linkedin.com', NULL, 'https://www.bing.com/', 'member', 'semester'),
('user4', 'Diana Evans', 'diana.evans@example.com', 'Computer Science, BS', 'graduate', '2023-11-01', 
  '{"artificial intelligence"}', NULL, 'https://linkedin.com', 'https://github.com', NULL, 'user', NULL),
('user5', 'Evan Wright', 'evan.wright@example.com', 'Philosophy, BA', 'undergraduate', '2025-04-20', 
  '{"data science", "cloud computing"}', NULL, NULL, 'https://github.com', 'https://www.google.com/', 'member', 'annual');

-- Insert company 1
INSERT INTO companies (name, location, description, industry_id) values
('Tech Innovations', 'San Francisco, CA', 'Leading provider of AI-driven solutions', 'technology'),
('Eco Green Solutions', 'Austin, TX', 'Sustainable and renewable energy provider', 'energy'),
('Global Finance Corp', 'New York, NY', 'International financial services and investments', 'banking and finance'),
('Health Plus', 'Boston, MA', 'Healthcare technology and medical devices', 'healthcare'),
('Future Automotive', 'Detroit, MI', 'Next-generation automotive manufacturing', 'automotive');

INSERT INTO projects (name, description) values
('AI Chatbot', 'An intelligent chatbot using natural language processing'),
('Weather App', 'A weather forecasting app using open weather API'),
('Task Manager', 'A task management tool to organize daily activities'),
('Portfolio Website', 'A personal portfolio website built with React and Tailwind CSS'),
('Inventory System', 'A desktop application for managing inventory in small businesses');

-- Insert event 1
INSERT INTO events (
    name, location, start_date, end_date, description, event_type, 
    event_capacity, start_time, end_time, tags, target_audience, image, member_only
) 
VALUES (
    'Tech Conference 2024', 'San Francisco, CA', '2024-11-01', '2024-11-03', 
    'A three-day conference on the latest in technology and innovation.', 
    'conference', 500, '09:00', '17:00', 
    '{"artificial intelligence", "machine learning"}', 'students', 'event1.png', false
),
('Hackathon 2024', 'New York, NY', '2024-12-10', '2024-12-12', 
    'A 48-hour hackathon focused on software development and innovation.', 
    'hackathon', 300, '08:00', '20:00', 
    '{"networking"}', 'students', 'event2.png', false
),
(
    'Data Science Workshop', 'Boston, MA', '2024-09-15', '2024-09-15', 
    'A one-day workshop on data science fundamentals and techniques.', 
    'workshop', 150, '10:00', '16:00', 
    '{"data science"}', 'students', 'event3.png', true
);

INSERT INTO event_companies(event_id, company_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(2, 1),
(2, 3),
(2, 4),
(3, 5),
(3, 3);

INSERT INTO subscribed_events(user_id, event_id) VALUES
('user1', 1),
('user1', 2),
('user2', 1),
('user2', 3),
('user4', 2),
('user4', 1),
('user3', 3),
('user5', 1),
('user5', 2),
('user5', 3);

INSERT INTO subscribed_companies(user_id, company_id) VALUES
('user1', 1),
('user1', 2),
('user1', 5),
('user2', 1),
('user2', 2),
('user2', 3),
('user2', 4),
('user2', 5),
('user3', 2),
('user3', 4),
('user3', 5),
('user4', 3),
('user4', 4),
('user4', 5);

INSERT INTO interested_in_projects(user_id, project_id) VALUES
('user1', 1),
('user1', 3),
('user2', 2),
('user2', 5),
('user3', 1),
('user3', 2),
('user3', 3),
('user3', 4),
('user3', 5),
('user5', 2),
('user5', 3),
('user5', 4);

INSERT INTO equipment_rental_type (name, price, description) VALUES
('Laptop Rental', 150.00, 'High-performance laptop rental for projects or events.'),
('Projector Rental', 80.00, 'HD projector rental for presentations or meetings.'),
('Camera Rental', 120.00, 'Professional DSLR camera rental for photography.'),
('VR Headset Rental', 100.00, 'Virtual reality headset rental for gaming or events.'),
('Tablet Rental', 50.00, NULL);

INSERT INTO equipment_item(equipment_type) VALUES
(1),
(1),
(1),
(1),
(1),
(1),
(1),
(2),
(2),
(2),
(3),
(3),
(3),
(3),
(3),
(4),
(4),
(5),
(5),
(5),
(5),
(5);
