name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: acm_website
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup
          with:
            os: ${{ runner.os }}
        - name: Run typecheck
          env:
            NODE_ENV: test
            PORT: 5001
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: acm_website
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URI: http://localhost:5001/api/v1/auth/callback
          run: |
              docker run --network host \
                  -e NODE_ENV -e PORT -e POSTGRES_HOST -e POSTGRES_PORT -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_DB \
                  -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e GOOGLE_REDIRECT_URI \
                  acm-website-server bun typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref }}

        - uses: ./.github/actions/setup
          with:
            os: ${{ runner.os }}
        - name: Run linter
          run: |
            docker run --network host \
                -e NODE_ENV -e PORT -e POSTGRES_HOST -e POSTGRES_PORT -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_DB \
                -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e GOOGLE_REDIRECT_URI \
                acm-website-server bun run lint

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: acm_website
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 15s
    steps:
      - uses: actions/checkout@v4 
      - uses: ./.github/actions/setup
        with:
          os: ${{ runner.os }}

      - name: Validate SQL Scripts
        run: |
          EXIT_CODE=0
          echo "Validating 01_createdb.sql"
          PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d acm_website -v ON_ERROR_STOP=1 -f ./db-scripts/01_createdb.sql || EXIT_CODE=$?
          echo "Validating 02_insert_data.sql"
          PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d acm_website -v ON_ERROR_STOP=1 -f ./db-scripts/02_insert_data.sql || EXIT_CODE=$?
          exit $EXIT_CODE

      - name: Run tests
        env:
          NODE_ENV: test
          PORT: 5001
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: acm_website
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: http://localhost:5001/api/v1/auth/callback
        run: |
          docker run --network host \
            -e NODE_ENV -e PORT -e POSTGRES_HOST -e POSTGRES_PORT -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_DB \
            -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e GOOGLE_REDIRECT_URI \
            acm-website-server bun test

  generate-types:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: acm_website
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4 
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: ./.github/actions/setup
        with:
          os: ${{ runner.os }}

      - name: Start server
        env:
          NODE_ENV: test
          PORT: 5001
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: acm_website
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: http://localhost:5001/api/v1/auth/callback
        run: |
          docker run --network host \
            -e NODE_ENV -e PORT -e POSTGRES_HOST -e POSTGRES_PORT -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_DB \
            -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e GOOGLE_REDIRECT_URI \
            acm-website-server

      - name: Wait for backend OpenAPI documentation endpoint to be available
        run: |
          max_retries=6
          retry_count=0
          poll_interval=10          

          until curl --fail http://localhost:5001/docs; do
            sleep $poll_interval
            retry_count=$((retry_count + 1))
            if [ $retry_count -ge $max_retries ]; then
              echo "http://localhost:5001/docs not available"
              exit 1
            fi
          done

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Generate types
        working-directory: ./client
        run: |
          bun install 
          bun run generate-types

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push generated types
        working-directory: ./client
        run: |
          if git diff --quiet HEAD -- "src/types/schema.v1.d.ts"; then
            echo "No generated types to commit"
          else
            echo "Commiting and pushing generated types"
            git add src/types/schema.v1.d.ts
            git commit -m "generate openapi types [skip ci]"
            git push origin ${{ github.event.pull_request.head.ref }}
          fi

#  build:
#    needs: [typecheck, lint, test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4

#      - name: Build
#        run: |
#          cd ./server
#          docker build --target=run --no-cache .
