name: CI

on:
  push:
    branches:
      - '**' # currently run on all branches
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd server
          bun install

      - name: Run tests
        run: |
          cd server
          bun test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd server
          bun install

      - name: Run linter
        run: |
          cd server
          bun run lint

  pr-check:
    if: github.event_name == 'pull_request'
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: PR is ready to be merged
        run: echo "All checks passed. PR is ready to be merged."
